<a href="https://colab.research.google.com/github/ccastaneda-boot/etl-data-pipeline/blob/main/notebooks/Aseguradas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv

In [1]:
import pandas as pd

In [2]:
url="https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"

In [3]:
df = pd.read_csv(url)

In [4]:
df.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

EXPLORACIÓN DE DATOS

In [5]:
#Exploración de datos:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            13 non-null     object
 3   rating_riesgo   12 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes

id_aseguradora    0
nombre            0
pais              2
rating_riesgo     3
dtype: int64

LIMPIEZA DE DATOS

In [6]:
aseguradoras = df.copy()

In [7]:
#Elimina espacios al inicio y al final en columnas de texto
aseguradoras.columns = aseguradoras.columns.str.strip().str.lower()

In [8]:
#Elimina espacios al inicio y al final de cada dato de las columnas de tipo "object" (string)
for col in aseguradoras.select_dtypes(include='object').columns:
    aseguradoras[col] = aseguradoras[col].astype(str).str.strip()

In [9]:
#Reemplaza espacios o vacios en celdas por pd.NA (valor nulo estándar de pandas)
aseguradoras = aseguradoras.replace(r'^\s*$', pd.NA, regex=True)

In [10]:
aseguradoras = aseguradoras.drop_duplicates()

In [11]:
aseguradoras["nombre"] = aseguradoras["nombre"].str.title()
aseguradoras["pais"] = aseguradoras["pais"].str.title()

map_rating = {
    "alto": "Alto",
    "medio": "Medio",
    "bajo": "Bajo"
}

aseguradoras["rating_riesgo"] = aseguradoras["rating_riesgo"].str.lower().map(map_rating)
aseguradoras["rating_riesgo"] = aseguradoras["rating_riesgo"].fillna("No especificado")
aseguradoras["pais"] = aseguradoras["pais"].fillna("No especificado")

In [12]:
aseguradoras.head()

   id_aseguradora         nombre         pais    rating_riesgo
0               1  Aseguradora 1   Costa Rica             Alto
1               2  Aseguradora 2  El Salvador             Bajo
2               3  Aseguradora 3  El Salvador  No especificado
3               4  Aseguradora 4   Costa Rica            Medio
4               5  Aseguradora 5   Elsalvador  No especificado

SEPARAR DATOS VALIDOS Y RECHAZADOS

In [13]:
validos = aseguradoras[
    aseguradoras['nombre'].notna() &
    aseguradoras['pais'].notna() &
    aseguradoras['rating_riesgo'].notna()
].copy()

In [14]:
rechazados = aseguradoras[
    aseguradoras['nombre'].isna() |
    aseguradoras['pais'].isna() |
    aseguradoras['rating_riesgo'].isna()
].copy()

MOTIVO DE RECHAZO

In [15]:
def motivo(row):

    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['pais']):
        motivos.append("pais_vacio")


    if pd.isna(row['rating_riesgo']):
        motivos.append("rating_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

EXPORTAR ARCHIVOS

In [16]:
validos.to_csv("aseguradoras_curated.csv", index=False)

In [17]:
rechazados.to_csv("aseguradoras_rejects.csv", index=False)

In [18]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd
database_url = "postgresql://etl_seguros_qs2b_user:vt9HawjFLorrA2FFsCn16HfhQrnZh6qi@dpg-d6qu5q3uibrs739hdpa0-a.oregon-postgres.render.com/etl_seguros_qs2b"
engine = create_engine(database_url)
test = pd.read_sql('SELECT 1', engine)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 45.8 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

Cargar Data a la DB

In [19]:
validos.to_sql(
    'aseguradoras_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'aseguradoras_rejects',
    engine,
    if_exists='append',
    index=False
)

0

Validar Carga

In [20]:
pd.read_sql(
"SELECT * FROM aseguradoras_curated LIMIT 10",
engine
)

   id_aseguradora          nombre         pais    rating_riesgo
0               1   Aseguradora 1   Costa Rica             Alto
1               2   Aseguradora 2  El Salvador             Bajo
2               3   Aseguradora 3  El Salvador  No especificado
3               4   Aseguradora 4   Costa Rica            Medio
4               5   Aseguradora 5   Elsalvador  No especificado
5               6   Aseguradora 6          Nan            Medio
6               7   Aseguradora 7    Guatemala             Alto
7               8   Aseguradora 8       Panamá             Bajo
8               9   Aseguradora 9          Nan             Bajo
9              10  Aseguradora 10       Panamá  No especificado