<a href="https://colab.research.google.com/github/ccastaneda-boot/etl-data-pipeline/blob/main/notebooks/Polizas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv

In [3]:
import pandas as pd

In [1]:
url="https://raw.githubusercontent.com/ccastaneda-boot/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv"

In [4]:
df = pd.read_csv(url)

In [5]:
df.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

EXPLORACIÓN DE DATOS

In [6]:
#Exploración de datos:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB

id_poliza             0
fecha_emision      2411
id_cliente            0
id_corredor           0
id_aseguradora        0
id_tipo_seguro        0
prima              3310
comision           3435
monto_asegurado    3363
dtype: int64

In [7]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
0

LIMPIEZA DE DATOS

In [8]:
polizas = df.copy()

In [9]:
#Elimina espacios al inicio y al final en columnas de texto
polizas.columns = polizas.columns.str.strip().str.lower()

In [10]:
#Elimina espacios al inicio y al final de cada dato de las columnas de tipo "object" (string)
for col in polizas.select_dtypes(include='object').columns:
    polizas[col] = polizas[col].astype(str).str.strip()

In [11]:
#Reemplaza espacios o vacios en celdas por pd.NA (valor nulo estándar de pandas)
polizas = polizas.replace(r'^\s*$', pd.NA, regex=True)

In [12]:
polizas = polizas.drop_duplicates()

In [16]:
#Convertir fecha de emision en formato fecha

polizas['fecha_emision'] = pd.to_datetime(polizas['fecha_emision'], errors='coerce')

In [17]:
polizas.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaT,184,42,15,2,"829,53",nan,139253.11
1,2,2026-02-16,2408,35,11,12,nan,"12,22","27.544,32"
2,3,NaT,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,NaT,2821,40,10,5,1866.62,456.99,244461.27
4,5,NaT,945,23,9,11,-,"324,08",123407.75

SEPARAR DATOS VALIDOS Y RECHAZADOS

In [19]:
validos = polizas[
    polizas['fecha_emision'].notna() &
    polizas['prima'].notna() &
    polizas['comision'].notna()&
    polizas['monto_asegurado'].notna()
].copy()

In [20]:
rechazados = polizas[
    polizas['fecha_emision'].notna() |
    polizas['prima'].notna()  |
    polizas['comision'].notna() |
    polizas['monto_asegurado'].notna()
].copy()

MOTIVO DE RECHAZO

In [21]:
def motivo(row):

    motivos = []

    if pd.isna(row['fecha_emision']):
        motivos.append("fecha_emicion_vacio")

    if pd.isna(row['prima']):
        motivos.append("prima_vacio")


    if pd.isna(row['comision']):
        motivos.append("comision_vacio")

    if pd.isna(row['monto_asegurado']):
        motivos.append("monto_asegurado_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

EXPORTAR ARCHIVOS

In [22]:
validos.to_csv("polizas_curated.csv", index=False)

In [23]:
rechazados.to_csv("polizas_rejects.csv", index=False)

In [24]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd
database_url = "postgresql://etl_seguros_qs2b_user:vt9HawjFLorrA2FFsCn16HfhQrnZh6qi@dpg-d6qu5q3uibrs739hdpa0-a.oregon-postgres.render.com/etl_seguros_qs2b"
engine = create_engine(database_url)
test = pd.read_sql('SELECT 1', engine)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 37.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

Cargar Data a la DB

In [25]:
validos.to_sql(
    'polizas_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'polizas_rejects',
    engine,
    if_exists='append',
    index=False
)

150

Validar Carga

In [30]:
pd.read_sql(
"SELECT * FROM polizas_curated LIMIT 10",
engine
)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,2,2026-02-16,2408,35,11,12,nan,"12,22","27.544,32"
1,10,2026-01-24,2281,69,13,3,791.38,"67,44",20710.00
2,26,2025-07-29,2295,71,11,4,614.46,"149,78",36670.97
3,31,2025-08-07,1847,45,4,2,nan,"229,13","117.309,88"
4,32,2025-07-28,388,22,6,4,822.52,-,nan
5,45,2025-12-11,2278,66,3,11,1539.37,240.41,"114,732.26"
6,48,2025-07-16,259,29,14,1,nan,46.88,55688.51
7,49,2025-08-11,1122,2,14,4,337.32,69.59,47210.14
8,50,2025-02-22,717,49,15,10,518.78,"86,45","66.871,99"
9,66,2025-03-04,1352,21,12,6,776.33,147.21,112829.12